site_name: TI4 References
nav:
  - index.md
  - Rules Summary: rules-summary.md
  - Tech:
    - tech/tech-trees.md
  - Factions:
    - factions.md
    - Base Game:
      - Arborec: factions/base/arborec.md
      - Ghosts of Creuss: factions/base/creuss.md
      - Emirates of Hacan: factions/base/hacan.md
      - Universities of Jol-Nar: factions/base/jolnar.md
      - L1Z1X Mindnet: factions/base/l1z1x.md
      - Barony of Letnev: factions/base/letnev.md
      - Embers of Muaat: factions/base/muaat.md
      - Mentak Coalition: factions/base/mentak.md
      - Naalu Collective: factions/base/naalu.md
      - Nekro Virus: factions/base/nekro.md
      - Clan of Saar: factions/base/saar.md
      - Sardakk N'orr: factions/base/sardakk.md
      - Federation of Sol: factions/base/sol.md
      - Winnu: factions/base/winnu.md
      - Xxcha Kingdom: factions/base/xxcha.md
      - Yin Brotherhood: factions/base/yin.md
      - Yssaril Tribes: factions/base/yssaril.md
    - Prophecy of Kings:
      - Argent Flight: factions/pok/argent.md
      - Vuil'raith Cabal: factions/pok/cabal.md
      - Empyrean: factions/pok/empyrean.md
      - Mahact Gene-Sorcerers: factions/pok/mahact.md
      - Naaz-Rokha Alliance: factions/pok/naaz.md
      - Nomad: factions/pok/nomad.md
      - Titans of Ul: factions/pok/titans.md
    - Codices:
      - Council Keleres: factions/codex/keleres.md
      - Liberation of Ordinian:
        - Crimson Rebellion: factions/codex/redcreuss.md
        - Nekro Virus: factions/codex/ordiniannekro.md
        - Salient Sun (alliance): factions/codex/salientsun.md
    - Thunder's Edge:
      - Last Bastion: factions/te/bastion.md
      - Crimson Rebellion: factions/te/crimson.md
      - Ral Nel Consortium: factions/te/ralnel.md
    - Discordant Stars:
      - Shipwrights of Axis: factions/ds/axis.md
      - Bentor Conglomerate: factions/ds/bentor.md
      - Celdauri Trade Federation: factions/ds/celdauri.md
      - Cheiran Hordes: factions/ds/cheiran.md
      - Savages of Cymiae: factions/ds/cymiae.md
      - Dih-Mohn Flotilla: factions/ds/dihmohn.md
      - Edyn Mandate: factions/ds/edyn.md
      - Florzen Profiteers: factions/ds/florzen.md
      - Free Systems Compact: factions/ds/freesystems.md
      - Ghemina Raiders: factions/ds/ghemina.md
      - GLEdge Union: factions/ds/gledge.md
      - Augurs of Ilyxum: factions/ds/ilyxum.md
      - Kollecc Society: factions/ds/kollecc.md
      - Mirveda Protectorate: factions/ds/mirveda.md
      - Glimmer of Mortheus: factions/ds/mortheus.md
      - Myko-Mentori: factions/ds/mykomentori.md
      - Nokar Sellships: factions/ds/nokar.md
      - Nivyn Star Kings: factions/ds/nivyn.md
      - Olradin League: factions/ds/olradin.md
      - Zealots of Rhodun: factions/ds/rhodun.md
      - Roh'Dhna Mechatronics: factions/ds/rohdhna.md
      - Vaden Banking Clans: factions/ds/vaden.md
      - Vaylerian Scourge: factions/ds/vaylerian.md
      - Zelian Purifier: factions/ds/zelian.md
  - Units: units.md
  - Promissory Notes: promissory-notes.md
  - Alliances: alliances.md
  - Relics: relics.md
  - Legendary Planets: legendary-planets.md
  - Bounce House Trophy Wall: bounce-house.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navgiation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
markdown_extensions: 
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: "¶"
