site_name: TI4 References
nav:
  - index.md
  - Rules Summary: rules-summary.md
  - Tech:
    - tech/tech-trees.md
  - Factions:
    - factions.md
    - Base Game:
      - Arborec: factions/base/arborec.md
      - Barony of Letnev: factions/base/letnev.md
      - Clan of Saar: factions/base/saar.md
      - Embers of Muaat: factions/base/muaat.md
      - Emirates of Hacan: factions/base/hacan.md
      - Federation of Sol: factions/base/sol.md
      - Ghosts of Creuss: factions/base/ghost.md
      - L1Z1X Mindnet: factions/base/l1z1x.md
      - Mentak Coalition: factions/base/mentak.md
      - Naalu Collective: factions/base/naalu.md
      - Nekro Virus: factions/base/nekro.md
      - Sardakk N'orr: factions/base/sardakk.md
      - Universities of Jol-Nar: factions/base/jolnar.md
      - Winnu: factions/base/winnu.md
      - Xxcha Kingdom: factions/base/xxcha.md
      - Yin Brotherhood: factions/base/yin.md
      - Yssaril Tribes: factions/base/yssaril.md
    - Prophecy of Kings:
      - Argent Flight: factions/pok/argent.md
      - Empyrean: factions/pok/empyrean.md
      - Mahact Gene-Sorcerers: factions/pok/mahact.md
      - Naaz-Rokha Alliance: factions/pok/naaz.md
      - Nomad: factions/pok/nomad.md
      - Titans of Ul: factions/pok/titans.md
      - Vuil'raith Cabal: factions/pok/cabal.md
    - Codices:
      - Council Keleres: factions/codex/keleres.md
    - Discordant Stars:
      - Shipwrights of Axis: factions/ds/axis.md
      - Celdauri Trade Federation: factions/ds/celdauri.md
      - Dih-Mohn Flotilla: factions/ds/dihmohn.md
      - Florzen Profiteers: factions/ds/florzen.md
      - Mirveda Protectorate: factions/ds/mirveda.md
      - Nivyn Star Kings: factions/ds/nivyn.md
      - Vaden Banking Clans: factions/ds/vaden.md
      - Vaylerian Scourge: factions/ds/vaylerian.md
      - GLEdge Union: factions/ds/gledge.md
  - Units: units.md
  - Promissory Notes: promissory-notes.md
  - Relics: relics.md
  - Bounce House Trophy Wall: bounce-house.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navgiation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
markdown_extensions: 
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: "¶"
