site_name: TI4 References
nav:
  - index.md
  - Rules Summary: rules-summary.md
  - Tech:
    - tech/tech-trees.md
  - Factions:
    - Arborec: factions/arborec.md
    - Argent Flight: factions/argent.md
    - Barony of Letnev: factions/letnev.md
    - Clan of Saar: factions/saar.md
    - Council Keleres: factions/keleres.md
    - Embers of Muaat: factions/muaat.md
    - Emirates of Hacan: factions/hacan.md
    - Empyrean: factions/empyrean.md
    - Federation of Sol: factions/sol.md
    - Ghosts of Creuss: factions/ghost.md
    - L1Z1X Mindnet: factions/l1z1x.md
    - Mahact Gene-Sorcerers: factions/mahact.md
    - Mentak Coalition: factions/mentak.md
    - Naalu Collective: factions/naalu.md
    - Naaz-Rokha Alliance: factions/naaz.md
    - Nekro Virus: factions/nekro.md
    - Nomad: factions/nomad.md
    - Sardakk N'orr: factions/sardakk.md
    - Titans of Ul: factions/titans.md
    - Universities of Jol-Nar: factions/jolnar.md
    - Vuil'raith Cabal: factions/cabal.md
    - Winnu: factions/winnu.md
    - Xxcha Kingdom: factions/xxcha.md
    - Yin Brotherhood: factions/yin.md
    - Yssaril Tribes: factions/yssaril.md
  - Units: units.md
  - Promissory Notes: promissory-notes.md
  - Relics: relics.md
  - Bounce House: bounce-house.md
extra_css:
  - stylesheets/extra.css
theme:
  name: material
  palette: 
    # Palette toggle for light mode
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  custom_dir: overrides
  features:
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.sections
    - navigation.top
    - navgiation.tracking
    - navigation.tabs
    - navigation.tabs.sticky
    - toc.integrate
markdown_extensions: 
  - admonition
  - attr_list
  - md_in_html
  - pymdownx.extra
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      options:
        custom_icons:
          - overrides/.icons
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - tables
  - toc:
      permalink: "¶"
